# Modifications Copyright(C)[2026] Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------------
# Licensed under the Apache-2.0 License
# ------------------------------------------------------------------------------------
independent_first_frame: false
warp_denoising_step: false
weight_decay: 0.01
same_step_across_blocks: true
discriminator_lr_multiplier: 1.0
last_step_only: false
i2v: false
num_training_frames: 21
gc_interval: 100
context_noise: 0
causal: true
ckpt_step: 0
prompt_name: Vidprom
prompt_path: prompts/vidprom_filtered_extended.txt
eval_first_n: 64
num_samples: 1
height: 480
width: 832
num_frames: 81